# Generated by Django 5.0.6 on 2024-06-22 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Avantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_depart', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SegmentHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium')], max_length=100)),
                ('avantages', models.ManyToManyField(related_name='car_types', to='reservations.avantage')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=100)),
                ('nombre_places', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='reservations.cartype')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrivee', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree', models.IntegerField(default=480, help_text='Durée en minutes')),
                ('horairesegment', models.ManyToManyField(blank=True, related_name='segments', to='reservations.segmenthoraire')),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_depart', models.DateField(default=django.utils.timezone.now)),
                ('adress_depart', models.CharField(max_length=50)),
                ('adress_arrivee', models.CharField(max_length=50)),
                ('nom_voyage', models.CharField(blank=True, max_length=100)),
                ('arrets', models.ManyToManyField(related_name='Trajet', to='reservations.arret')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trajet', to='reservations.cars')),
                ('horaires', models.ManyToManyField(related_name='Trajet', to='reservations.horaire')),
                ('segments', models.ManyToManyField(related_name='Trajet', to='reservations.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reservation', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('nombre_de_place', models.IntegerField(default=1)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.client')),
                ('segment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.segment')),
                ('trajet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.trajet')),
            ],
        ),
        migrations.CreateModel(
            name='TrajetSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_segment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('place_disponible', models.IntegerField(default=0)),
                ('segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.segment')),
                ('trajet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.trajet')),
            ],
        ),
        migrations.AddField(
            model_name='arret',
            name='ville',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.ville'),
        ),
    ]
