# Generated by Django 5.0.6 on 2024-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajetsegment',
            name='prix_segment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
