# Generated by Django 5.0.6 on 2024-06-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='ordre',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
