# Generated by Django 5.0.6 on 2024-06-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_trajetsegment_prix_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='horairesegment',
            field=models.ManyToManyField(blank=True, null=True, related_name='segments', to='reservations.segmenthoraire'),
        ),
    ]
