# Generated by Django 5.0.6 on 2024-06-22 12:59

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_ville_ordre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prix_segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(choices=reservations.models.get_ville_choices, max_length=50)),
                ('arrivee', models.CharField(choices=reservations.models.get_ville_choices, max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='trajet',
            name='adress_arrivee',
            field=models.CharField(choices=reservations.models.get_ville_choices, max_length=50),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='adress_depart',
            field=models.CharField(choices=reservations.models.get_ville_choices, max_length=50),
        ),
    ]
