# Generated by Django 5.0.6 on 2024-06-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_prix_segment_alter_trajet_adress_arrivee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='prix',
        ),
    ]
