# Generated by Django 5.0.6 on 2024-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_segment_horairesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
