# Generated by Django 5.0.6 on 2024-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_trajet_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='arrets',
            field=models.ManyToManyField(blank=True, related_name='Trajet', to='reservations.arret'),
        ),
    ]
