# Generated by Django 5.0.6 on 2024-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_segment_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetsegment',
            name='place_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
