# Generated by Django 5.0.6 on 2024-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_trajet_arrets'),
    ]

    operations = [
        migrations.AddField(
            model_name='prix_segment',
            name='duree',
            field=models.IntegerField(default=480, help_text='Durée en minutes'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='duree',
            field=models.IntegerField(help_text='Durée en minutes'),
        ),
    ]
