# Generated by Django 5.0.6 on 2024-06-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_trajetsegment_place_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='segments',
            field=models.ManyToManyField(null=True, related_name='Trajet', to='reservations.segment'),
        ),
    ]
