# Generated by Django 5.0.6 on 2024-06-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_prix_segment_duree_alter_segment_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajetsegment',
            name='place_disponible',
        ),
        migrations.CreateModel(
            name='HoraireSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_disponible', models.IntegerField(default=0)),
                ('segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaire_segments', to='reservations.segment')),
                ('segmenthoraire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.segmenthoraire')),
            ],
        ),
    ]
