# Generated by Django 5.0.6 on 2024-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_trajet_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='segments',
            field=models.ManyToManyField(blank=True, null=True, related_name='Trajet', to='reservations.segment'),
        ),
    ]
