# Generated by Django 5.0.6 on 2024-06-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_segmentsegmenthoraire_delete_horairesegmenths'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SegmentSegmentHoraire',
            new_name='Segment_Horaire',
        ),
    ]
