# Generated by Django 5.0.6 on 2024-06-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_trajet_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='segments',
            field=models.ManyToManyField(related_name='Trajet', to='reservations.segment'),
        ),
    ]
