# Generated by Django 5.0.6 on 2024-06-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_rename_segmentsegmenthoraire_segment_horaire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Segment_Horaire',
            new_name='SegmentSegmentHoraire',
        ),
    ]
