# Generated by Django 5.0.6 on 2024-06-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_rename_segment_horaire_segmentsegmenthoraire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='segment_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='trajet_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='segmenthoraire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.segmentsegmenthoraire'),
        ),
    ]
