# Generated by Django 5.0.6 on 2024-06-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_trajet_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='nombre_de_place',
            field=models.IntegerField(default=1),
        ),
    ]
