# Generated by Django 5.0.6 on 2024-06-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_remove_reservation_segment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant_reservation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
