# Generated by Django 5.0.6 on 2024-06-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_reservation_nombre_de_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
