# Generated by Django 5.0.6 on 2024-06-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_alter_reservation_numero_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Korhogo', 'Korhogo'), ('Bouaké', 'Bouaké'), ('Yamoussoukro', 'Yamoussoukro'), ('Abidjan', 'Abidjan')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trajet',
            name='arrets',
            field=models.ManyToManyField(related_name='Trajet', to='reservations.arret'),
        ),
    ]
