# Generated by Django 5.0.6 on 2024-06-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_arret_trajet_arrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='horairesegment',
            field=models.ManyToManyField(blank=True, related_name='segments', to='reservations.segmenthoraire'),
        ),
    ]
